name: Test against Antora Versions

on:
  push:
    branches: [ '**' ]
    paths:
      - 'lib/antora/**'
      - 'test/**'
      - 'package.json'
      - '.github/workflows/test-antora.yml'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'lib/antora/**'
      - 'test/**'
      - 'package.json'
      - '.github/workflows/test-antora.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        antora-version: ['~3.1', '3.2.0-alpha.8']

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Install specific Antora version
        run: |
          npm install --no-save @antora/cli@${{ matrix.antora-version }} @antora/site-generator@${{ matrix.antora-version }}
          # Ensure Asciidoctor is at ~2.2 as required by Antora
          npm install --no-save @asciidoctor/core@~2.2
        
      - name: Run Antora tests
        env:
          # Force CI mode and logging settings
          CI: "true"
          FORCE_COLOR: "1"
          ANTORA_LOG_FORMAT: "json"
          ANTORA_LOG_LEVEL: "all"
          DEBUG: "antora:*"
        run: |
          # Make the test script executable
          chmod +x tests/antora/run-antora.sh
          
          # Run tests with CI-specific settings
          npx jest tests/antora --verbose --no-colors
