name: Test against Asciidoctor Versions

on:
  push:
    branches: [ '**' ]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'package.json'
      - '.github/workflows/test-asciidoctor.yml'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'package.json'
      - '.github/workflows/test-asciidoctor.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        include:
          # Test with Asciidoctor 2.2 on all Node versions
          - asciidoctor-version: '~2.2'
            node-version: '18.x'
          - asciidoctor-version: '~2.2'
            node-version: '20.x'
          - asciidoctor-version: '~2.2'
            node-version: '22.x'
          # Only test Asciidoctor 3.0 on Node 20 for now as it's experimental
          - asciidoctor-version: '~3.0'
            node-version: '20.x'
            experimental: true

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Install specific Asciidoctor version
        run: npm install --no-save @asciidoctor/core@${{ matrix.asciidoctor-version }}
        
      - name: Run Asciidoctor tests
        continue-on-error: ${{ matrix.experimental || false }}
        run: npx jest tests/asciidoctor 
